version: '3.9'

services:
  dagster_webserver:
    container_name: dagster_webserver
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: 
      - dagster-webserver
      - --host
      - "0.0.0.0"
      - --port
      - "3000"
      - --workspace
      - "dagster_home/workspace.yml"
    environment:
      - DAGSTER_POSTGRES_USER=${POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
      - DAGSTER_POSTGRES_DB=personal_finance
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      - dagster_postgres
      - pipeline_personal_finance
    expose:
      - "3000"
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  dagster_daemon:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    environment:
      - DAGSTER_POSTGRES_USER=${POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
      - DAGSTER_POSTGRES_DB=personal_finance
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      - dagster_postgres
      - pipeline_personal_finance

  pipeline_personal_finance:
    container_name: pipeline_personal_finance
    build:
      context: ./pipeline_personal_finance
      dockerfile: dockerfile
    environment:
      USER_ID: 1000
      GRP_ID: 1000
      TIMEZONE: Australia/Melbourne
      DAGSTER_HOME: /docker/appdata/dagster/dagster_home
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: test
      DAGSTER_POSTGRES_IP: postgres
      DAGSTER_POSTGRES_PORT: 5432
    volumes:
      - .:/docker/appdata/dagster/pipeline_personal_finance
    networks:
      - dagster_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  dagster_postgres:
    image: postgres:16
    shm_size: 128mb
    restart: always
    container_name: dagster_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=personal_finance
      - PUID=${USER_ID}
      - PGID=${GRP_ID}
      - TZ=${TIMEZONE}
    ports:
      - "5432:5432"
    volumes:
      - /docker/appdata/postgres:/var/lib/postgresql/data
    networks:
      - dagster_network

networks:
  dagster_network:
    driver: bridge
    name: dagster_network
