# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the Docker image
WORKDIR /docker/appdata/dagster/pipeline_personal_finance

# Copy the current directory contents into the container at the specified directory
COPY . .

# Install the required dependencies
RUN pip install -r requirements.txt

# Expose the port that Dagster gRPC server uses
EXPOSE 4000

# Command to run the Dagster gRPC server
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "pipeline_personal_finance"]
